version: '3.9'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass
    volumes: 
      - ../redis:/data

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
      - "8000"
    volumes:
      - ./apps/web/src:/usr/app/apps/web/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "/probe"]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - ./services/api/src:/usr/app/services/api/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=todoiti
